kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build
  image: golang:1.10
  commands:
  - cd posix
  - tar -xf fixtures.tar -C /
  - go test -v

- name: docker-prod-push
  image: plugins/docker
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  settings:
    dockerfile: docker/Dockerfile.linux.amd64
    username: drone
    password:
      from_secret: harbor_drone_pass
    repo: harbor.shipttech.com/plugins/${DRONE_REPO_NAME}
    registry: harbor.shipttech.com
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    build_args_from_env:
      - GITHUB_TOKEN
  when:
    event:
      include:
        - tag

- name: docker-beta-push
  image: plugins/docker
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  settings:
    dockerfile: docker/Dockerfile.linux.amd64
    username: drone
    password:
      from_secret: harbor_drone_pass
    repo: harbor.shipttech.com/plugins/${DRONE_REPO_NAME}
    registry: harbor.shipttech.com
    tags:
      - beta
      - ${DRONE_COMMIT_SHA}
    build_args_from_env:
      - GITHUB_TOKEN
  when:
    event:
      exclude:
        - tag
    branch:
      - main